# Generated by Django 6.0.4 on 2026-04-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.IntegerField(help_text='Weight in kilograms'),
        ),
    ]
