# Generated by Django 6.0.4 on 2026-04-27 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
